#==============================================
# SETTINGS for running the DA code.
# Some options are listed in curly brackets.
# See the README.md file for more explaination.
#==============================================

# Location of data and lipd directories
data_dir: '/projects/pd_lab/data/data_assimilation/'
data_dir: '/Users/chrishancock/Library/CloudStorage/OneDrive-NorthernArizonaUniversity/Research/Manuscript/DAMP12k/Data/'

# Primary options
exp_name: 'LakesDefault.AssimilateSequential'     # The experiment name, which will be appended to the filename. Pick something short & memorable, using only letters, numbers, and underscores.
vars_to_reconstruct:   ['tas','LakeStatus']  # The variables to reconstruct {['tas','precip']}.
season_to_reconstruct: 'annual' # The season to reconstruct {'annual','jja','djf'}
time_resolution:       500      # The base temporal resolution, in years {10}
maximum_resolution:    1000     # The maximum temporal resolution to assimilate proxies at, in years {1000}
prior_window:          10000     # The size of the window for the time-varying prior, in years {'all',5010,1010}
prior_mean_always_0:   False    # Is the mean of the prior allowed to change through time? {True,False}. If true, the mean of the prior is always 0.
assimate_together:     False     # If False, assimile proxies one at a time (slower) {True,False}
localization_radius:   15000     # Localization radius, in meters {None,15000}  Only works if assimate_together=False
percent_of_prior:      100      # What percentage of the prior states to assimilate {100}.  Note, a value of 8.7 -> 100 ens, if other settings are default
seed_for_prior:        0        # This seed is only used if 'percent_of_prior' is below 100 {0}

# Proxies to assimilate
assimilate_selected_seasons:    ['annual']  # Assimilate proxies with the selected seasonality. Note, the reconstruction will still try to represent annual means. {False, ['annual','summeronly','winteronly','summer+','winter+'], 'jja_preferred', 'djf_preferred'}
assimilate_selected_archives:   False  # Provide a list of one or more archive types to assimilate {False, ['LakeSediment','MarineSediment','Peat','GlacierIce','Midden','Speleothem','Wood','Ice-other']}
assimilate_selected_HCproxies:  ['LakeStatus']     #Provide a list of one or more hydroclimate proxy types to assimilate ['CalibratedPollen','CalibratedOther','LakeStatus']
assimilate_selected_region:     False  # Provide bounds to assimilate only proxies in a given region {False, [lat_min,lat_max,lon_min,lon_max]} using lons between 0-360.
assimilate_selected_resolution: False  # Assimilate proxies with median resolutions in a given band {False, [0,100]}.  Bounds are [inclusive,exclusive].
percent_to_assimilate:          85    # What percentage of proxies to assimilate {100}
seed_for_proxy_choice:          0      # This seed is only used if 'percent_to_assimilate' is below 100 {0}

# Models for prior {['hadcm3_regrid','trace_regrid','famous_regrid','DAMP12kTraCE']}
models_for_prior: ['DAMP12kTraCE']

# Proxy datasets {['temp12k','hydro12k'],['pages2k'],['pseudo_temp12k_using_trace_noise_whiteproxyrmse_tas']}
proxy_datasets_to_assimilate: ['hydro12k']#['pseudo_hydro12k_using_DAMP12kTraCE_noise_none_LakeStatus']
version_temp12k:              '1_0_2' # The version of temp12k to use, if it's included in 'proxy_datasets_to_assimilate' {'1_0_2','1_1_0'}
version_hydro12k:             '0_7_0' # The version of temp12k to use, if it's included in 'proxy_datasets_to_assimilate' {'0_7_0'}#TODO

# Age ranges
age_range_to_reconstruct: [0,22000]
reference_period:         [0,2000]  # This is only used if 'reconstruction_type' is set to 'relative'
age_range_model:          [0,22000]

# Experimental options (These options are less well-tested or may not be fully implemented. Edit with care.)
age_uncertain_method:  False     # If True, age uncertainty is incorporated in the proxy values and time-varying uncertainty; if False, the original method is used, with a single-value R value. This only works if "time_resolution" is set to 10 {True,False}
reconstruction_type: 'relative'  # Reconstruction absolute or relative values {'relative','absolute'}.  If 'absolute', prior_mean_always_0 is ignored.
model_processing:    None        # Processing the model prior {None,'linear_global','linear_spatial',None}
assign_seasonality:  False       # If something other than false, all proxies are set to specific seasonalities {False,'annual','summer','winter','jja','djf'}
change_uncertainty:  False       # Change uncertainty values in several ways {False,'mult_#','all_#','path/to/file.txt'}
   # False    Use values from metadata.
   # 'mult_#' Multiply uncertainty values from metadata by a constant number.
   # 'all_#'  Set uncertainty values to a constant number.
   # 'path/to/file.txt' Use uncertainty values from a text file. The file must contain TSids and new MSE values for each proxy.
