#==============================================
# SETTINGS for running the DA code.
# Some options are listed in curly brackets.
# See the README.md file for more explaination.
#==============================================

# Location of data and lipd directories
data_dir: 'C:/Users/erbm/Documents/data_climate/data_assimilation/'

# Primary options
exp_name: 'eco21ka'  # The experiment name, which will be appended to the filename. Pick something short & memorable, using only letters, numbers, and underscores.
vars_to_reconstruct:   ['tas_annual','tas_month_01','tas_month_02','tas_month_03','tas_month_04','tas_month_05','tas_month_06','tas_month_07','tas_month_08','tas_month_09','tas_month_10','tas_month_11','tas_month_12']  # The variables to reconstruct {['tas','precip']}, then season after underscore (e.g., "annual", "jja", "djf", "month_01", "month_02").
time_resolution:       100      # The base temporal resolution, in years {100}
maximum_resolution:    100      # The maximum temporal resolution to assimilate proxies at, in years {100}
prior_window:          5100     # The size of the window for the time-varying prior, in years {'all',5010,1010}
assimate_together:     False    # If False, assimilate proxies one at a time (slower) {True,False}
localization_radius:   5000     # Localization radius, in km {None,5000}  Only works if assimate_together=False
percent_of_prior:      100      # What percentage of the prior states to assimilate {100}
seed_for_prior:        0        # This seed is only used if 'percent_of_prior' is below 100 {0}

# Proxies to assimilate
proxies_to_use: ['temperature|temperature|any|any|degC|calibrated_tas']  # Proxies to assimilate, in the format of interp|variable|archive|proxy|units|psm. Use "any" to select anything in a category. "psm" specifies the PSM to use. Use commas to select multiple values in a category. Available psms: calibrated_tas, calibrated_precip, calibrated_tas_nearest, calibrated_precip_nearest, rank_based_tas, rank_based_precip
assimilate_selected_seasons:    ['annual','summer','winter']  # Assimilate proxies with the selected seasonality. Note, the reconstruction will still try to represent annual means. {False, ['annual','summeronly','winteronly','summer+','winter+'], 'jja_preferred', 'djf_preferred'}
assimilate_selected_archives:   False  # Provide a list of one or more archive types to assimilate {False, ['LakeSediment','MarineSediment','Peat','GlacierIce','Midden','Speleothem','Wood','Ice-other']}
assimilate_selected_region:     False  # Provide bounds to assimilate only proxies in a given region {False, [lat_min,lat_max,lon_min,lon_max]} using lons between 0-360.
assimilate_selected_resolution: False  # Assimilate proxies with median resolutions in a given band {False, [0,100]}.  Bounds are [inclusive,exclusive].
percent_to_assimilate:          100    # What percentage of proxies to assimilate {100}
seed_for_proxy_choice:          0      # This seed is only used if 'percent_to_assimilate' is below 100 {0}
average_nearby_proxies:         True  # If True, average together proxy records within 1km of each other {True,False}  NOTE: Not yet implemented

# Models for prior
models_for_prior: ['trace']   # The model to use {['trace','itrace','hadcm3','trace_downscaled']}
model_region: [-5,89,180,360]  # The region to reconstruct {[-90,90,0,360]}

# Proxy datasets
proxy_datasets_to_assimilate: ['ecoclimate_selected_ts_2026-07-16']

# Age ranges
age_range_to_reconstruct: [0,21000]
reference_period:         [3000,5000]  # This is only used if 'reconstruction_type' is set to 'relative'
age_range_model:          [0,22000]

# Experimental options (These options are less well-tested or may not be fully implemented. Edit with care.)
reconstruction_type: 'relative'  # Reconstruction absolute or relative values {'relative','absolute'}
restrict_kalman:     False       # If True, cov/var in the kalman gain equation is not allowed to be smaller than 0 or larger than 1 {True, False} NOTE: currently only works with assilimate_together=False
model_processing:    None        # Processing the model prior {None,'linear_global','linear_spatial','highpass_spatial'}
assign_seasonality:  False       # If something other than false, all proxies are set to specific seasonalities {False,'annual','summer','winter','jja','djf'}
change_uncertainty:  'all_0.5'   # Change uncertainty values in several ways {False,'mult_#','all_#','stdev_#','path/to/file.txt'}
   # False     Use values from metadata.
   # 'mult_#'  Multiply uncertainty values from metadata by a constant number.
   # 'all_#'   Set uncertainty values to a constant number.
   # 'stdev_#' Set uncertainty of each record to the standard deviation of that record, multiplied by the value given.
   # 'var_#' Set uncertainty of each record to the variance of that record, multiplied by the value given.
   # 'varmodel_#' Set uncertainty of each record to the variance of the model at that point (time varying), multiplied by the value given.
   # 'path/to/file.txt' Use uncertainty values from a text file. The file must contain TSids and new MSE values for each proxy.

